### ISSUE TITLE
exportApps is creating empty folder

### ISSUE THREAD

**Issue by mattachawki** [apigeecs/apigee-migrate-tool#32] opened 2019-09-24 15:04 UTC
apps are not exported , empty folders created instead

**Comment by karsten-wagner** [comment] 2020-02-10 15:08
I have found the same behavior. When running "grunt exportApps -v" on my public cloud Apigee organization, majority of the folders created for developers remain empty. I have ~250 developers and I got the apps exported only for around 5 of them.

I am not a node.js developer, thus had some trouble tracing the issue. Seems the problem is in file /tasks/app.js somewhere around method iterateOverDevs (line 85). I had the impression the function is not properly iterating. However when it came to reading the app details, it seems for all developers I ran into line 36 of that file, but only for a few to line 38... Not sure if this helps, but wanted to share what I knew...

**Comment by kurtkanaskie** [comment] 2020-02-19 20:00
Ah, found the problem, iterateOverDevs was calling done() when it needed to still wait for callbacks to finish.

Note, that you may see an empty folder if there's an App developer with no Apps.

**Comment by karsten-wagner** [comment] 2020-02-20 08:34
Fix from PR #39 works for me...

**Comment by SnehansuBhuyan** [comment] 2020-06-01 16:34
Hi , need help urgently . When running "grunt exportApps -v" in Apigee public cloud , I am seeing only the emailIDs but no app under email ID. From the log , I could see below. Please suggest me the fix. 
$ grunt exportApps
Running "exportApps" task
>> Retrieved 35 developers
>> Retrieved total of 35 developers

**Comment by SnehansuBhuyan** [comment] 2020-06-01 21:06
> Hmmm, be sure you are using the pull request from this forked repo:
> https://github.com/kurtkanaskie/apigee-migrate-tool?organization=kurtkanaskie&organization=kurtkanaskie
> Its not been merged into this repo yet.
> 
> I just verified in my org:
> 
> ```
> $ grunt exportApps 
> Running "exportApps" task
> >> Retrieved 32 developers
> >> Retrieved TOTAL of 32 developers, waiting for callbacks to complete
>  ...
> >> Exported 73 apps for 32 developers
> ```

Thank You . Its working .
I have another question, when running "grunt exportProxies" from my prod environment , but its exporting from latest version the proxy not the proxies deployed to prod environment . Please suggest how to make this using this tool.

**Comment by SnehansuBhuyan** [comment] 2020-06-01 22:07
I have another question, when running "grunt exportProxies" from my prod environment , but its exporting from latest version the proxy not the proxies deployed to prod environment . My requirement is to export all the prod environment api and import to new org. Please suggest how to make this using this tool.

**Comment by kurtkanaskie** [comment] 2020-06-02 11:31
That's how it's currently implemented, please open a new issue.

**Comment by SnehansuBhuyan** [comment] 2020-06-02 12:56
Thanks @kurtkanaskie for your response.
I am having a issue in the "import app". I have 140 Apps and exported all Apps in the data folder. While running "grunt importApps", 
- only 70 Apps imported . rest of the Apps not imported . 
- Also "Credential" section is empty for all import Apps. I want credential section also import.
EX- data/apps/XXXXX@XXXX.com/AMEX-DEV-MANAGER-API-700_REGISTERED_NOT_VERIFIED this kind of not import . Any issue here ?

Please help me to fix these TWO issues.

**Comment by SnehansuBhuyan** [comment] 2020-06-02 14:36
Hi @kurtkanaskie , requesting you to please provide your suggestion for the above questions.

**Comment by kurtkanaskie** [comment] 2020-06-02 14:51
On quick test it appears there is an issue with importKeys. Please open an issue.
I'll take a look at importApps but it worked in a quick test for 73 of my app export / import.

**Comment by SnehansuBhuyan** [comment] 2020-06-02 15:23
Import App is not working as expected. #43 -- Created a new issue . Please help me to fix .

**Comment by kurtkanaskie** [comment] 2020-06-04 14:04
Hi @SnehansuBhuyan I've fixed an issue with importKeys in my repo:
https://github.com/kurtkanaskie/apigee-migrate-tool
which will be part of this pull request:
https://github.com/apigeecs/apigee-migrate-tool/pull/39

I'll also comment on your issue #43

**Comment by kurtkanaskie** [comment] 2021-01-06 19:27
Verified

**Closed** 2021-01-06 19:26 UTC
